// Data dictionary for study exports. Descriptions are looked up per file
// first, then from the shared column list; anything else is listed as
// "recorded by the client" so every exported column appears in the codebook.

const COMMON = {
  id: 'Server row id (unique within the file).',
  study_id: 'Study identifier.',
  device_id: 'Pseudonymous device identifier (random UUID assigned by the app). Link to participant codes via devices.csv.',
  timestamp: 'Event time as epoch milliseconds, UTC (for derived daily files: local midnight of the day).',
  created_at: 'When the server stored the row (ISO 8601, UTC).',
  event_id: 'Client-generated unique id used to drop duplicate uploads.',
  seq: 'Per-device sequence number shared by client_events and device_state; gaps indicate rows lost in transit.',
  timezone: 'IANA time zone of the phone when the row was recorded (or used to compute local dates).',
  utc_offset_minutes: 'Offset of the phone clock from UTC in minutes when recorded.',
  platform: 'ios or android.',
  app_version: 'StudyTrace app version.',
  build_number: 'StudyTrace app build number.',
  device_id_source: 'Source of the device id.',
};

const FILES = {
  'raw/locations': {
    double_latitude: 'Latitude (WGS84 degrees).',
    double_longitude: 'Longitude (WGS84 degrees).',
    double_accuracy: 'Horizontal accuracy radius in meters (lower is better).',
    double_altitude: 'Altitude in meters.',
    double_speed: 'Speed in m/s when reported.',
    double_bearing: 'Bearing in degrees when reported.',
    provider: 'Location provider.',
  },
  'raw/plugin_device_usage': {
    elapsed_device_on: 'iOS: milliseconds the phone was unlocked in the session that just ended (row written at lock). 0 on unlock rows.',
    elapsed_device_off: 'iOS: milliseconds the phone was locked before this unlock (row written at unlock = a pickup). 0 on lock rows.',
  },
  'raw/android_screen_events': {
    event: 'Android screen event: unlock, lock, screen_on, or screen_off.',
  },
  'raw/android_app_usage': {
    date: 'Local calendar day (YYYY-MM-DD) covered by the row.',
    package_name: 'Android package name.',
    app_label: 'App name shown to the user.',
    foreground_seconds: 'Seconds the app was in the foreground that day (from UsageStatsManager events).',
    launch_count: 'Number of times the app came to the foreground that day.',
    window_start: 'Start of the day window, epoch ms.',
    window_end: 'End of the day window, epoch ms.',
    construct: 'Measurement construct (foreground_time).',
    dedupe_key: 'Idempotency key (one row per day and package).',
  },
  'raw/client_events': {
    event_name: 'App event (e.g. app_launch, heartbeat, notification_delivered, notification_tapped, permission_changed, usage_screenshot_upload_succeeded).',
    app_state: 'App state when recorded: active, inactive, or background.',
    metadata: 'Event details as JSON (e.g. launch_reason, notification_id, delivered_at, is_survey_prompt, permission/from/to).',
  },
  'raw/device_state': {
    reason: 'What triggered the snapshot (launch, foreground, background, consent).',
    battery_level: 'Battery level from 0 to 1.',
    battery_state: 'Charging state.',
    low_power_mode_enabled: 'Whether Low Power Mode was on.',
    notification_authorization: 'Notification permission.',
    location_authorization: 'Location permission (authorized_always, authorized_when_in_use, denied, ...).',
    location_accuracy_authorization: 'Precise (full) or approximate (reduced) location.',
    background_refresh_status: 'iOS Background App Refresh: available, denied, or restricted.',
    usage_access: 'Android usage-access permission: granted or denied.',
    free_disk_mb: 'Free storage in MB.',
    system_name: 'Operating system name.',
    system_version: 'Operating system version.',
    device_model: 'Device model family.',
  },
  battery_usage_apps: {
    app_name: 'App name read from the Settings > Battery screenshot.',
    screen_time_seconds: 'On-screen time for the app in the screenshot window, seconds.',
    screen_time_text: 'On-screen time as displayed.',
    battery_percent: 'Share of battery used by the app, percent.',
    battery_percent_text: 'Battery share as displayed.',
    usage_window: 'Time range selected in the screenshot: last_24_hours or last_10_days (participant-confirmed).',
    captured_at: 'When the screenshot was taken (from image metadata), ISO 8601 UTC.',
    participant_edited: 'True if the participant corrected the values read on the phone.',
    extraction_status: 'confirmed (participant reviewed), parsed (server OCR), or a failure status.',
    extraction_method: 'participant_confirmed, tesseract, provided_text, or none.',
    ocr_confidence: 'Server OCR confidence (0-100) when server OCR was used.',
    needs_review: 'True if the values should be checked against the screenshot.',
    qa_reason: 'Why the row needs review.',
    parse_notes: 'Parser notes.',
    ocr_text: 'Text recognized from the screenshot (on-device OCR when confirmed).',
    source_sensor: 'Table holding the source screenshot.',
    source_row_id: 'Row id of the source screenshot.',
    source_image_url: 'Dashboard URL of the screenshot image (researcher login required).',
  },
  screen_time_activity: {
    row_type: 'summary (daily totals) or app (one most-used app).',
    activity_date: 'Day shown in the Screen Time screenshot (participant-confirmed).',
    app_name: 'App name (app rows).',
    screen_time_seconds: 'App screen time that day, seconds (app rows).',
    total_screen_time_seconds: 'Total screen time that day, seconds (summary rows).',
    pickups: 'Total pickups that day (summary rows).',
    notifications: 'Total notifications that day (summary rows).',
    captured_at: 'When the screenshot was taken, ISO 8601 UTC.',
    participant_edited: 'True if the participant corrected the values read on the phone.',
    extraction_status: 'confirmed, parsed, or needs_review.',
    extraction_method: 'participant_confirmed or a server OCR method.',
    needs_review: 'True if totals or app rows could not be read.',
    qa_reason: 'Why the row needs review.',
    ocr_text: 'Text recognized from the screenshot.',
    source_sensor: 'Table holding the source screenshot.',
    source_row_id: 'Row id of the source screenshot.',
    source_image_url: 'Dashboard URL of the screenshot image.',
  },
  phone_use_daily: {
    date: 'Participant-local calendar day (YYYY-MM-DD).',
    pickups: 'Unlocks that day.',
    total_use_seconds: 'Unlocked time that day, seconds (sessions split at local midnight).',
    session_count: 'Unlock-to-lock sessions starting that day.',
    median_session_seconds: 'Median session length, seconds.',
    short_session_share: 'Share of sessions shorter than 60 seconds (fragmentation).',
    long_session_count: 'Sessions of 15 minutes or longer.',
    night_use_seconds: 'Unlocked time between 00:00 and 05:00 local, seconds.',
    first_use_at: 'Start of the first use that day, ISO 8601 UTC.',
    last_use_at: 'End of the last use that day, ISO 8601 UTC.',
    source_rows: 'Lock/unlock rows available for the device (iOS records these only while StudyTrace runs).',
  },
  location_daily_summary: {
    date: 'Participant-local calendar day (YYYY-MM-DD).',
    location_rows: 'Location fixes that day.',
    first_location_at: 'First fix, ISO 8601 UTC.',
    last_location_at: 'Last fix, ISO 8601 UTC.',
    coverage_minutes: 'Minutes between first and last fix.',
    distance_meters: 'Path length between consecutive fixes (jumps over 10 km excluded), meters.',
    radius_of_gyration_meters: 'Spread of locations around their centroid, meters.',
    stop_count: 'Places within 100 m where the participant stayed 15 minutes or longer.',
    mean_accuracy_meters: 'Mean reported accuracy, meters.',
    max_accuracy_meters: 'Worst reported accuracy, meters.',
  },
  survey_quality: {
    source_sensor: 'Table holding the survey answer.',
    source_row_id: 'Row id of the survey answer.',
    question_title: 'Question title.',
    question_trigger: 'Question identifier (esm_trigger).',
    question_type: 'AWARE ESM type (1 text, 2 radio, 3 checkbox, 4 likert, 9 numeric, 13 clock, 14 photo, ...).',
    answered: 'True if an answer was recorded.',
    esm_status: 'AWARE status code: 0 new, 1 dismissed, 2 answered, 3 expired.',
    status_label: 'esm_status as text.',
    answer_kind: 'text, photo, json, or empty.',
    answer_length: 'Answer length in characters.',
    response_latency_seconds: 'Seconds from prompt to answer.',
    submitted_at: 'Answer time, ISO 8601 UTC.',
    local_date: 'Participant-local date of the answer.',
    quality_flags: 'Semicolon-separated flags (missing_answer, dismissed, expired, long_latency, required_missing, photo_response).',
  },
  participant_health: {
    participant: 'Participant label from the join link.',
    last_seen: 'Last server contact, ISO 8601 UTC.',
    last_client_event: 'Latest telemetry event time.',
    last_heartbeat: 'Latest hourly heartbeat time.',
    max_telemetry_gap_hours_24h: 'Longest stretch without telemetry in the last 24 hours, hours.',
    last_launch_reason: 'Why the app last started: user, location, remote_notification, or background.',
    last_device_state: 'Latest device-state snapshot time.',
    prompts_delivered_7d: 'Distinct survey prompts reported delivered/presented/tapped in 7 days.',
    survey_sessions_7d: 'Answered survey sessions in 7 days.',
    compliance_rate_7d: 'survey_sessions_7d / prompts_delivered_7d (capped at 1).',
    surveys_dismissed_7d: 'Surveys dismissed in 7 days.',
    surveys_expired_7d: 'Surveys that expired in 7 days.',
    telemetry_missing_7d: 'Telemetry rows lost in transit in 7 days (sequence gaps).',
    permission_changes_7d: 'Permission changes in 7 days.',
    health_status: 'ok or needs_attention.',
    notes: 'Reasons for needs_attention.',
  },
  app_usage_combined: {
    date: 'Local calendar day the value refers to (screenshot capture day for Battery rows).',
    construct: 'What was measured: battery_on_screen_time (iOS Battery screenshot; window per usage_window), screen_time_app_total (iOS Screen Time screenshot, one day), or foreground_time (Android UsageStats, one day). These are different constructs; compare with care.',
    usage_window: 'Window the value covers: last_24_hours, last_10_days, day, or unknown.',
    app_name: 'App name.',
    package_name: 'Android package name (Android rows).',
    seconds: 'Usage in seconds for the window.',
    source: 'battery_screenshot, screen_time_screenshot, or android_usage_stats.',
    extraction_method: 'participant_confirmed, server OCR method, or usage_stats.',
    participant_edited: 'True if the participant corrected screenshot values.',
  },
  devices: {
    participant: 'Participant label from the join link (?participant=...).',
    first_seen: 'First contact, ISO 8601 UTC.',
    last_seen: 'Last contact, ISO 8601 UTC.',
  },
  withdrawals: {
    participant: 'Participant label at the time of withdrawal.',
    source: 'Who requested it: participant, researcher, or admin.',
    delete_data: 'True if uploaded data was deleted.',
    rows_deleted: 'Rows deleted.',
    requested_at: 'When the withdrawal happened, ISO 8601 UTC.',
  },
};

const ESM_COLUMNS = {
  esm_trigger: 'Question identifier.',
  esm_json: 'Question definition as shown (JSON).',
  esm_user_answer: 'Answer. Photo answers are replaced by image:<file> (see media/ when images are included).',
  esm_status: 'AWARE status code: 0 new, 1 dismissed, 2 answered, 3 expired.',
  double_esm_user_answer_timestamp: 'Answer time, epoch ms UTC.',
  esm_expiration_threshold: 'Expiration window of the prompt.',
  screenshot_kind: 'battery or screen_time_activity (screenshot uploads).',
  upload_id: 'SHA-256 of the uploaded image (idempotency key).',
  confirmed_rows: 'Values the participant confirmed on the phone (JSON).',
  confirmed_summary: 'Screen Time totals the participant confirmed (JSON).',
  participant_confirmed: 'True if the participant reviewed the values on the phone.',
  device_ocr_text: 'Text recognized on the phone.',
};

export function describeColumn(file, column) {
  const fileKey = file.replace(/\.csv$/, '');
  if (FILES[fileKey]?.[column]) return FILES[fileKey][column];
  if (/raw\/(esms|plugin_ios_esm|ios_esm)$/.test(fileKey) && ESM_COLUMNS[column]) return ESM_COLUMNS[column];
  if (COMMON[column]) return COMMON[column];
  return 'Recorded by the client; see the AWARE sensor documentation for this table.';
}
